mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

mysite/jamup/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='jamup'
urlpatterns = [
    path('', views.PostListView.as_view()),
    path('jamup', views.PostListView.as_view(), name='all'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/create',
        views.PostCreateView.as_view(success_url=reverse_lazy('jamup:all')), name='post_create'),
    path('post/<int:pk>/update',
        views.PostUpdateView.as_view(success_url=reverse_lazy('jamup:all')), name='post_update'),
    path('post/<int:pk>/delete',
        views.PostDeleteView.as_view(success_url=reverse_lazy('jamup:all')), name='post_delete'),
    path('post/<int:pk>/reply',
        views.ReplyCreateView.as_view(), name='post_reply_create'),
    path('reply/<int:pk>/delete',
        views.ReplyDeleteView.as_view(success_url=reverse_lazy('jamup:all')), name='post_reply_delete'),
    path('jamup/profiles', views.ProfileListView.as_view(), name='all_profiles'),
    path('profile/<int:pk>', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('profile/create',
        views.ProfileCreateView.as_view(success_url=reverse_lazy('jamup:all_profiles')), name='profile_create'),
    path('profile/<int:pk>/update',
        views.ProfileUpdateView.as_view(success_url=reverse_lazy('jamup:all_profiles')), name='profile_update'),
    path('profile/<int:pk>/delete',
        views.ProfileDeleteView.as_view(success_url=reverse_lazy('jamup:all')), name='profile_delete'),
    path('profile_picture/<int:pk>', views.stream_file, name='profile_picture'),
    path('jamup/messages', views.MessageListView.as_view(), name='my_messages'),
    path('message/create',
        views.MessageCreateView.as_view(success_url=reverse_lazy('jamup:my_messages')), name='message_create'),
    path('message/<int:pk>/delete',
        views.MessageDeleteView.as_view(success_url=reverse_lazy('jamup:my_messages')), name='message_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('jamup.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/jamup/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from jamup.humanize import naturalsize
from jamup.models import Post, Profile, Message


# Create the form class.
class CreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'city', 'state', 'reason', 'text']

class ReplyForm(forms.Form):
    reply = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

class ProfileCreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Profile
        fields = ['name', 'picture', 'city', 'state', 'bio', 'genres', 'instruments', 'private']
        labels = {'picture': 'Upload a profile picture (portrait images look best!)', 'private': 'Checking this box will prevent your profile from appearing on the profiles page'}


    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(ProfileCreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

class MessageCreateForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['recipient', 'text']

mysite/jamup/views.py
from jamup.models import Post, Reply, Profile, Message
from jamup.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView, OwnerDeleteViewMessage
from jamup.forms import CreateForm, ReplyForm, ProfileCreateForm, MessageCreateForm

from django.core.files.uploadedfile import InMemoryUploadedFile

from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

class PostListView(OwnerListView):
    model = Post
    template_name = "jamup/post_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(title__contains=strval)
            query.add(Q(text__contains=strval), Q.OR)
            query.add(Q(city__name__contains=strval), Q.OR)
            query.add(Q(state__name__contains=strval), Q.OR)
            query.add(Q(reason__name__contains=strval), Q.OR)
            objects = Post.objects.filter(query).select_related().order_by('-updated_at')
        else :
            # try both versions with > 4 posts and watch the queries that happen
            objects = Post.objects.all().order_by('-updated_at')
            # objects = Post.objects.select_related().all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        post_list = objects

        ctx = {'post_list' : post_list, 'search': strval}
        retval = render(request, self.template_name, ctx)

        return retval


class PostDetailView(OwnerDetailView):
    model = Post
    template_name = 'jamup/post_detail.html'

    def get(self, request, pk) :
        x = Post.objects.get(id=pk)
        replies = Reply.objects.filter(post=x).order_by('-updated_at')
        reply_form = ReplyForm()
        context = { 'post' : x, 'replies': replies, 'reply_form': reply_form }
        return render(request, self.template_name, context)


class PostCreateView(OwnerCreateView):
    model = Post
    fields = ['title', 'city', 'state', 'reason', 'text']

    template_name = 'jamup/post_form.html'
    success_url = reverse_lazy('jamup:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        prof = get_object_or_404(Profile, user=self.request.user)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        post = form.save(commit=False)
        post.owner = self.request.user
        post.profile = prof
        post.save()
        return redirect(self.success_url)


class PostUpdateView(OwnerUpdateView):
    model = Post
    fields = ['title', 'city', 'state', 'reason', 'text']

    template_name = 'jamup/post_form.html'
    success_url = reverse_lazy('jamup:all')

    def get(self, request, pk=None):
        post1 = get_object_or_404(Post, id=pk, owner=self.request.user)
        form = CreateForm(instance=post1)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        post1 = get_object_or_404(Post, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=post1)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        post1 = form.save(commit=False)
        post1.save()

        return redirect(self.success_url)


class PostDeleteView(OwnerDeleteView):
    model = Post

class ReplyCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        p = get_object_or_404(Post, id=pk)
        reply = Reply(text=request.POST['reply'], owner=request.user, post=p)
        reply.save()
        return redirect(reverse('jamup:post_detail', args=[pk]))

class ReplyDeleteView(OwnerDeleteView):
    model = Reply
    template_name = "jamup/reply_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        post1 = self.object.post
        return reverse('jamup:post_detail', args=[post1.id])

class ProfileListView(OwnerListView):
    model = Profile
    template_name = "jamup/profile_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # objects = Profile.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(name__contains=strval)
            query.add(Q(bio__contains=strval), Q.OR)
            query.add(Q(city__name__contains=strval), Q.OR)
            query.add(Q(state__name__contains=strval), Q.OR)
            query.add(Q(genres__contains=strval), Q.OR)
            query.add(Q(instruments__contains=strval), Q.OR)
            objects = Profile.objects.filter(query).select_related().order_by('-updated_at')
        else :
            # try both versions with > 4 posts and watch the queries that happen
            objects = Profile.objects.all().order_by('-updated_at')
            # objects = Post.objects.select_related().all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        profile_list = objects

        ctx = {'profile_list' : profile_list, 'search': strval}
        retval = render(request, self.template_name, ctx)

        return retval

class ProfileDetailView(OwnerDetailView):
    model = Profile
    template_name = 'jamup/profile_detail.html'

    def get(self, request, pk) :
        x = Profile.objects.get(id=pk)
        posts = Post.objects.filter(profile=x).order_by('-updated_at')
        profile_form = ProfileCreateForm()
        context = { 'profile' : x, 'posts': posts, 'profile_form': profile_form }
        return render(request, self.template_name, context)


class ProfileCreateView(OwnerCreateView):
    model = Profile
    fields = ['name', 'picture', 'city', 'state', 'bio', 'text', 'genres', 'instruments']

    template_name = 'jamup/profile_form.html'
    success_url = reverse_lazy('jamup:all')

    def get(self, request, pk=None):
        form = ProfileCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = ProfileCreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        return redirect(self.success_url)


class ProfileUpdateView(OwnerUpdateView):
    model = Profile
    fields = ['name', 'picture', 'city', 'state', 'bio', 'text', 'genres', 'instruments']

    template_name = 'jamup/profile_form.html'
    success_url = reverse_lazy('jamup:all')

    def get(self, request, pk):
        profile1 = get_object_or_404(Profile, id=pk, user=self.request.user)
        form = ProfileCreateForm(instance=profile1)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        profile1 = get_object_or_404(Profile, id=pk, user=self.request.user)
        form = ProfileCreateForm(request.POST, request.FILES or None, instance=profile1)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        profile1 = form.save(commit=False)
        profile1.save()

        return redirect(self.success_url)


class ProfileDeleteView(OwnerDeleteViewMessage):
    model = Profile

class MessageListView(OwnerListView):
    model = Message
    template_name = "jamup/message_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            query = Q(text__contains=strval)
            query.add(Q(sender__username__contains=strval), Q.OR)
            query.add(Q(recipient__username__contains=strval), Q.OR)
            objects = Message.objects.filter(query).select_related().order_by('-created_at')
        else :
            objects = Message.objects.all().order_by('-created_at')

        message_list = objects

        ctx = {'message_list' : message_list}
        retval = render(request, self.template_name, ctx)

        return retval

class MessageCreateView(OwnerCreateView):
    model = Message
    fields = ['recipient', 'text']

    template_name = 'jamup/message_form.html'
    success_url = reverse_lazy('jamup:all')

    def get(self, request, pk=None):
        form = MessageCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = MessageCreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        message = form.save(commit=False)
        message.sender = self.request.user

        message.save()

mysite/jamup/templates/jamup/message_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Message</h1>

<p>Are you sure you want to delete the message: {{ message }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/jamup/templates/jamup/message_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'jamup:all' %}';return false;">
  </form>
</p>
{% endblock %}

mysite/jamup/templates/jamup/message_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Messages</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'jamup:my_messages' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
{% if user.is_authenticated %}
{% if user.profile %}
<p><a class="main_link" href="{% url 'jamup:message_create' %}">Send a Message</a></p>
{% else %}
<p><a class="main_link" href="{% url 'jamup:profile_create' %}">Create a profile before sending a message</a></p>
{% endif %}
{% endif %}
<p>
{%if user.is_authenticated and user.profile %}
{% if message_list %}
<div>
    {% for message in message_list %}
    {% if message.sender == user or message.recipient == user %}
        <div class="post">
            <div class="post_main post_content">
                {% if message.sender == user %}
                <p>From: You | To: <a href="{% url 'jamup:profile_detail'  message.recipient.id %}">{{ message.recipient }}</a></p>
                {% else %}
                <p>From: <a href="{% url 'jamup:profile_detail'  message.sender.id %}">{{ message.sender }}</a> | To: You</p>
                {% endif %}
                <p>{{ message.text }}</p>
                <p style="color:black">
                    (<a href="{% url 'jamup:message_delete' message.id %}">Delete</a>)
                </p>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% else %}
<p>You have not sent or received any messages yet!</p>
{% endif %}
</p>
{% else %}
<p>Log in and create a profile to send and receive messages</p>
{% endif %}
<p>
{% if user.is_authenticated %}
<a class="main_link" href="{% url 'logout' %}?next={% url 'jamup:all' %}">Logout</a>
{% else %}
<a class="main_link" href="{% url 'login' %}?next={% url 'jamup:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

mysite/jamup/templates/jamup/post_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Post</h1>

<p>Are you sure you want to delete the post: {{ post }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/jamup/templates/jamup/post_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ post.updated_at|naturaltime }})
{% if post.owner == user %}
<a href="{% url 'jamup:post_update' post.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'jamup:post_delete' post.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<div class="title_by">
    <h1>{{ post.title }}</h1>
    <p>By: <a href = "{% url 'jamup:profile_detail' post.owner.profile.user.id %}">{{post.owner}}</a></p>
</div>
<div class="post post_deets">
    <div class="post_content post_text">
        <p>Location: {{ post.city }}, {{ post.state }}</p>
        <p>Reason: {{ post.reason }}</p>
        <p>{{ post.text }}</p>
    </div>
</div>
<div class="post" id="post_replies">
    <h2>Replies</h2>
    {% for reply in replies %}
    <p> {{ reply.text }}
    ({{ reply.updated_at|naturaltime }})
    {% if user == reply.owner %}
    <a href="{% url 'jamup:post_reply_delete' reply.id %}"><i class="fa fa-trash" style="color:black"></i></a>
    {% endif %}
    </p>
    {% endfor %}
</div>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'jamup:post_reply_create' post.id %}">
    {% csrf_token %}
    {{ reply_form|crispy }}
<input type="submit" value="Submit">
</form>
</p>
{% endif %}
<p>
<a class="main_link" href="{% url 'jamup:all' %}">All posts</a>
</p>
{% endblock %}

mysite/jamup/templates/jamup/post_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'jamup:all' %}';return false;">
  </form>
</p>
{% endblock %}

mysite/jamup/templates/jamup/post_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Posts</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'jamup:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
{% if user.is_authenticated %}
{% if user.profile %}
<p><a class="main_link" href="{% url 'jamup:post_create' %}">Create a Post</a></p>
{% else %}
<p><a class="main_link" href="{% url 'jamup:profile_create' %}">Create a profile before posting</a></p>
{% endif %}
{% endif %}
<p>
{% if post_list %}
<div>
  {% for post in post_list %}
    <div class="post">
        <div class="post_main">
            <h3>{{ post.title }}</h3>
            <div class="post_content">
                <p>By: <a href = "{% url 'jamup:profile_detail' post.owner.profile.user.id %}">{{post.owner}}</a></p>
                <p>Location: {{post.city}}, {{post.state}}</p>
                <p>Reason: {{post.reason}}</p>
                <p><a href="{% url 'jamup:post_detail'  post.id %}">(View Post)</p>
            </div>
            {% if post.owner == user %}
            <p style="color:black">
            (<a href="{% url 'jamup:post_update' post.id %}">Edit</a> |
            <a href="{% url 'jamup:post_delete' post.id %}">Delete</a>)
            </p>
            {% endif %}
        </div>
    </div>
  {% endfor %}
</div>
{% else %}
  <p>There are no posts in the database.</p>
{% endif %}
</p>
<p>
{% if user.is_authenticated %}
<a class="main_link" href="{% url 'logout' %}?next={% url 'jamup:all' %}">Logout</a>
{% else %}
<a class="main_link" href="{% url 'login' %}?next={% url 'jamup:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

mysite/jamup/templates/jamup/profile_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Profile</h1>

<p>Are you sure you want to delete your profile? This will delete all of your posts, replies, and profile information from the site,
and it cannot be reversed.</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/jamup/templates/jamup/profile_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% if profile.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'jamup:profile_picture' profile.id %}">
</div>
{% endif %}
<span style="float: right;">
(Updated {{ profile.updated_at|naturaltime }})
{% if profile.user == user %}
<a href="{% url 'jamup:profile_update' profile.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'jamup:profile_delete' profile.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<div class="pic_surround">
    {% if profile.content_type %}
    <img class="prof_pic" src="{% url 'jamup:profile_picture' profile.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <div class="info1">
        <h1>{{ profile.name }}</h1>
        <p>Username: {{ profile.user }}</p>
        <p>Location: {{ profile.city }}, {{ profile.state }}</p>
    </div>
</div>
<div class="info2">
    <div class="prof_content">
        <h2>Bio</h2>
        <p>{{ profile.bio }}</p>
        <br>
        <p>Genres: {{profile.genres}}</p>
        <p>Instruments: {{ profile.instruments }}</p>
    </div>
</div>
<div class="post">
    <div class="post_main">
        <h2>Submitted Posts</h2>
        <div class="post_content">
            {% if posts %}
            {% for post in posts %}
            <p><a href="{% url 'jamup:post_detail' post.id %}">{{ post.title }}</a>
            ({{ post.updated_at|naturaltime }})
            {% if user == post.owner %}
            <a href="{% url 'jamup:post_delete' post.id %}"><i class="fa fa-trash prof_del"></i></a>
            {% endif %}
            </p>
            {% endfor %}
            {% else %}
            <p>This user has not made any posts</p>
            {% endif %}
        </div>
    </div>
</div>
<p>
<a class="main_link" href="{% url 'jamup:all' %}">Home</a>
</p>
<p>
<a class="main_link" href="{% url 'jamup:all_profiles' %}">All Profiles</a>
</p>
{% endblock %}

mysite/jamup/templates/jamup/profile_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'jamup:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

mysite/jamup/templates/jamup/profile_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Profiles</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'jamup:all_profiles' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if profile_list %}
<div>
  {% for profile in profile_list %}
  {% if not profile.private %}
    <div class="post">
        <div class="post_main">
            <h3>{{ profile.user }}</h3>
            <div class="post_content">
                <p>Name: {{ profile.name }}</p>
                <p>Location: {{profile.city}}, {{profile.state}}</p>
                <p><a href="{% url 'jamup:profile_detail'  profile.id %}">(View Profile)</a></p>
            </div>
            {% if profile.user == user %}
            <p style="color:black">
            (<a href="{% url 'jamup:profile_update' profile.id %}">Edit</a> |
            <a href="{% url 'jamup:profile_delete' profile.id %}">Delete</a>)
            </p>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
  <p>There are no profiles in the database.</p>
{% endif %}
</p>
<p>
{% if user.is_authenticated %}
<a class="main_link" href="{% url 'logout' %}?next={% url 'jamup:all' %}">Logout</a>
{% else %}
<a class="main_link" href="{% url 'login' %}?next={% url 'jamup:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

mysite/jamup/templates/jamup/reply_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Reply</h1>

<p>Are you sure you want to delete</p>
<p>{{ reply.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'jamup:post_detail' reply.post.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}